# Generated by Django 5.2.17 on 2026-08-28 04:52

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_intro',
            field=models.TextField(blank=True, default='Plain-language research summaries, guidelines and reports - reviewed by the Olga Tennison Autism Research Centre, with new resources added regularly.', help_text="Short introduction shown under the 'Featured resources' heading."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_label',
            field=models.CharField(blank=True, default='Explore the library', max_length=40, verbose_name='primary button label'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_primary_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='primary button page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_label',
            field=models.CharField(blank=True, default='About the Hub', max_length=40, verbose_name='secondary button label'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_secondary_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='secondary button page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(default='Autism research you can use', help_text='The main headline. Keep it short and plain.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='One or two short paragraphs welcoming visitors.'),
        ),
        migrations.CreateModel(
            name='FeaturedResourceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_url', models.URLField(blank=True, verbose_name='or link to an external URL')),
                ('type_label', models.CharField(help_text='The kind of resource, e.g. "Lay summary", "Guideline", "Report".', max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(help_text='One or two plain-language sentences about the resource.')),
                ('read_time_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Approximate reading time, in minutes.', null=True)),
                ('topic_labels', models.CharField(blank=True, help_text='Comma-separated topic chips shown on the card, e.g. "early signs, children". Temporary until Knowledge library topics exist.', max_length=120)),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_cards', to='home.homepage')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='link to a page on this site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_url', models.URLField(blank=True, verbose_name='or link to an external URL')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('summary', models.TextField(help_text='One or two plain-language sentences about the news item.')),
                ('cta_label', models.CharField(default='Find out more', max_length=40, verbose_name='button label')),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_slides', to='home.homepage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='link to a page on this site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
