# Generated by Django 5.2.17 on 2026-09-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_featured_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_heading_line_2',
            field=models.CharField(blank=True, default='', help_text='Optional continuation, shown on a new line in the secondary brand colour. Both parts may wrap further on small screens.', max_length=120, verbose_name='heading second line'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(default='Autism research you can use', help_text='The start of the main headline, shown in the primary brand colour.', max_length=120, verbose_name='heading first line'),
        ),
    ]
