# Generated by Django 5.2.17 on 2026-09-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_hero_heading_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image',
        ),
    ]
