# Generated by Django 5.2.17 on 2026-09-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsslide',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='newsslide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newsslide',
            name='link_page',
        ),
        migrations.DeleteModel(
            name='FeaturedResourceCard',
        ),
        migrations.DeleteModel(
            name='NewsSlide',
        ),
    ]
