# Generated by Django 5.2.17 on 2026-09-10 01:32

import wagtail.fields
from django.db import migrations, models


def seed_hero_content(apps, schema_editor):
    database = schema_editor.connection.alias
    HomePage = apps.get_model("home", "HomePage")
    LibraryPage = apps.get_model("knowledge_library", "KnowledgeLibraryPage")

    # An existing revision may contain deliberately empty fields or an unpublished
    # draft. Leave edited pages and their revision history entirely to editors.
    for homepage in HomePage.objects.using(database).filter(latest_revision_id=None):
        updates = {}
        if not homepage.hero_heading_line_2 and homepage.hero_heading in (
            "", "Autism research you can use"
        ):
            updates["hero_heading"] = "Autism research"
            updates["hero_heading_line_2"] = "you can use"
        if not homepage.hero_intro:
            updates["hero_intro"] = HomePage._meta.get_field("hero_intro").get_default()
        if not homepage.hero_cta_primary_page_id:
            library = LibraryPage.objects.using(database).filter(
                path__startswith=homepage.path,
                depth=homepage.depth + 1,
                slug="knowledge-library",
                live=True,
            ).first()
            if library:
                updates["hero_cta_primary_page_id"] = library.pk
                if not homepage.hero_cta_primary_label:
                    updates["hero_cta_primary_label"] = "Explore the library"
        if updates:
            HomePage.objects.using(database).filter(pk=homepage.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_cards'),
        ('knowledge_library', '0002_create_knowledge_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(default='Autism research', help_text='The start of the main headline, shown in the primary brand colour.', max_length=120, verbose_name='heading first line'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading_line_2',
            field=models.CharField(blank=True, default='you can use', help_text='Optional continuation, shown on a new line in the secondary brand colour. Both parts may wrap further on small screens.', max_length=120, verbose_name='heading second line'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_intro',
            field=wagtail.fields.RichTextField(blank=True, default='<p>Welcome to the Australian Autism Knowledge Hub, where we turn autism research into clear, trustworthy information.</p><p>Find out what we know, what we’re still learning, and what it could mean for you.</p>', help_text='One or two short paragraphs welcoming visitors.'),
        ),
        # Keep seeded content on rollback; it may since have been edited.
        migrations.RunPython(seed_hero_content, migrations.RunPython.noop),
    ]
