# Generated by Django 5.2.17 on 2026-09-15 15:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_seed_hero_content'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Short introduction shown below the page title.')),
                ('body', wagtail.fields.StreamField([('section', 2), ('team_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': "Who's working at the Hub", 'max_length': 150, 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('name', 6), ('role', 7), ('bio', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'max_num': 12, 'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('heading', 3), ('intro', 4), ('members', 10)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
