# Generated by Django 5.2.17 on 2026-09-16 23:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_genericpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('section', 2), ('team_section', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 150, 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': "Who's working at the Hub", 'max_length': 150, 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol'], 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 5), ('name', 6), ('role', 7), ('bio', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'max_num': 12, 'min_num': 1}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 3), ('intro', 4), ('members', 10), ('partnership', 4), ('funding', 4), ('more_team_label', 11), ('more_team_url', 12)]], {})}),
        ),
    ]
