# Generated by Django 5.2.17 on 2026-09-08 01:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeLibraryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_intro', models.TextField(default='Every week we summarise one piece of autism research into a snapshot to help the community understand what it found, how much confidence to place in it, and what it might mean in everyday life.\nPractical guidelines, frameworks, and reports are also in the library. Start with a topic, or search using everyday words.', help_text='A short introduction to the knowledge library. Use plain text.', verbose_name='banner introduction')),
                ('topics_intro', models.TextField(default='Choose the topic closest to your question. Each topic page lists the snapshots, frameworks, guidelines and reports on that topic.', help_text='A short paragraph helping visitors choose a topic. Use plain text.', verbose_name='Browse by topic introduction')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('topic_key', models.SlugField(choices=[('understanding-autism', 'Understanding autism'), ('diagnosis-and-assessment', 'Diagnosis and assessment'), ('communication-sensory-and-movement', 'Communication, sensory and movement'), ('therapies-supports-and-services', 'Therapies, supports and services'), ('education-and-learning', 'Education and learning'), ('work-and-employment', 'Work and employment'), ('physical-health-and-healthcare', 'Physical health and healthcare'), ('mental-health-and-wellbeing', 'Mental health and wellbeing'), ('family-relationships-and-social-life', 'Family, relationships and social life'), ('daily-life-and-housing', 'Daily life and housing'), ('inclusion-rights-and-safety', 'Inclusion, rights and safety'), ('cross-cutting', 'Cross-cutting')], editable=False, max_length=60, verbose_name='fixed topic')),
                ('name', models.CharField(help_text='Maximum 60 characters.', max_length=60, verbose_name='topic name')),
                ('summary', models.CharField(help_text='One short sentence. Maximum 160 characters.', max_length=160)),
                ('icon', models.CharField(choices=[('understanding', 'Understanding autism'), ('diagnosis', 'Diagnosis and assessment'), ('communication', 'Communication'), ('supports', 'Supports and services'), ('school', 'Education and learning'), ('adulthood', 'Work and employment'), ('health', 'Physical health'), ('wellbeing', 'Mental health and wellbeing'), ('relationships', 'Relationships'), ('daily-life', 'Daily life'), ('inclusion', 'Inclusion and accessibility'), ('cross-cutting', 'Cross-cutting')], max_length=30)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_cards', to='knowledge_library.knowledgelibrarypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('page', 'topic_key'), name='unique_library_topic_card')],
            },
        ),
    ]
