# Generated by Django 5.2.17 on 2026-09-08 05:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import knowledge_library.models
import knowledge_library.validators
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_library', '0002_create_knowledge_library'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, default='Browse snapshots, frameworks, guidelines and reports.')),
            ],
            options={
                'abstract': False,
            },
            bases=(knowledge_library.models.FixedLibraryPathMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('full_summary', models.TextField(help_text='A plain-language introduction. Maximum 150 words.', validators=[knowledge_library.validators.MaxWordsValidator(150)])),
                ('short_summary', models.TextField(help_text='A short introduction for resource cards. Maximum 40 words.', validators=[knowledge_library.validators.MaxWordsValidator(40)])),
                ('citation', wagtail.fields.RichTextField(blank=True, help_text='Credit the source. Select text and use Link to add an external URL.')),
                ('resource_type', models.CharField(choices=[('snapshot', 'Snapshot'), ('framework', 'Framework'), ('guideline', 'Guideline'), ('report', 'Report')], max_length=20)),
                ('publication_date', models.DateField(default=django.utils.timezone.localdate)),
                ('review_date', models.DateField(blank=True, help_text='Leave blank until this resource has been reviewed.', null=True)),
                ('body', wagtail.fields.StreamField([('heading_2', 0), ('heading_3', 1), ('heading_4', 2), ('paragraph', 3), ('quote', 6), ('table', 14), ('image', 18), ('video', 24), ('audio', 28)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Section heading (level 2)', 'max_length': 160}), 1: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Subheading (level 3)', 'max_length': 160}), 2: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Subheading (level 4)', 'max_length': 160}), 3: ('knowledge_library.blocks.ResourceRichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'ol', 'ul', 'link', 'document-link', 'resource-primary', 'resource-secondary'], 'help_text': 'Write paragraphs and lists here. Use separate heading blocks for sections. Colour must not be the only way you communicate meaning.', 'template': 'knowledge_library/blocks/resource_text.html'}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name the table and explain what it shows.', 'max_length': 250}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Column headings', 'min_num': 1}), 10: ('wagtail.blocks.TextBlock', (), {'required': False}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Cells', 'min_num': 1}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Add one cell for each column heading, in the same order.', 'min_num': 1}), 13: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Select when the first column names each row.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('caption', 7), ('headers', 9), ('rows', 12), ('first_column_is_header', 13)]], {}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describe the information the image conveys. For a complex diagram, also explain it in the surrounding text.', 'max_length': 300, 'required': False}), 17: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Select only when the image adds no information. Leave alternative text empty for decorative images.', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('image', 15), ('alt_text', 16), ('decorative', 17), ('caption', 10)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive name for the video.', 'max_length': 200}), 20: ('wagtail.blocks.URLBlock', (), {'help_text': 'Direct web address of a video file, such as MP4. The host must permit cross-origin playback on this site.', 'validators': [django.core.validators.URLValidator(schemes=['http', 'https'])]}), 21: ('wagtail.blocks.URLBlock', (), {'help_text': 'WebVTT captions file in English, including speech and meaningful sounds. Its host must allow cross-origin access.', 'validators': [django.core.validators.URLValidator(schemes=['http', 'https'])]}), 22: ('knowledge_library.blocks.ResourceRichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'help_text': 'Include all speech, meaningful sounds and descriptions of important visual information.'}), 23: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Check the soundtrack describes essential visuals. If needed, use an audio-described version of the video.', 'label': 'Important visual information is described in the audio', 'required': True}), 24: ('wagtail.blocks.StructBlock', [[('title', 19), ('url', 20), ('captions_url', 21), ('transcript', 22), ('visual_information_in_audio', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'help_text': 'A descriptive name for the recording.', 'max_length': 200}), 26: ('wagtail.blocks.URLBlock', (), {'help_text': 'Direct web address of an audio file, such as MP3. The host must permit playback on this site.', 'validators': [django.core.validators.URLValidator(schemes=['http', 'https'])]}), 27: ('knowledge_library.blocks.ResourceRichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'help_text': 'Include all speech and meaningful sounds. The transcript is displayed below the player.'}), 28: ('wagtail.blocks.StructBlock', [[('title', 25), ('url', 26), ('transcript', 27)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(knowledge_library.models.FixedLibraryPathMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('topic_key', models.SlugField(choices=[('understanding-autism', 'Understanding autism'), ('diagnosis-and-assessment', 'Diagnosis and assessment'), ('communication-sensory-and-movement', 'Communication, sensory and movement'), ('therapies-supports-and-services', 'Therapies, supports and services'), ('education-and-learning', 'Education and learning'), ('work-and-employment', 'Work and employment'), ('physical-health-and-healthcare', 'Physical health and healthcare'), ('mental-health-and-wellbeing', 'Mental health and wellbeing'), ('family-relationships-and-social-life', 'Family, relationships and social life'), ('daily-life-and-housing', 'Daily life and housing'), ('inclusion-rights-and-safety', 'Inclusion, rights and safety'), ('cross-cutting', 'Cross-cutting')], editable=False, max_length=60, unique=True)),
                ('introduction', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(knowledge_library.models.FixedLibraryPathMixin, 'wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='knowledgelibrarypage',
            name='banner_intro',
            field=models.TextField(default='Explore plain-language summaries of autism research, alongside practical guidelines, frameworks and reports. Understand key findings, how much confidence to place in the evidence, and what it could mean in everyday life.', help_text='A short introduction to the knowledge library. Use plain text.', verbose_name='banner introduction'),
        ),
        migrations.AlterField(
            model_name='knowledgelibrarypage',
            name='topics_intro',
            field=models.TextField(default='Each topic page lists the snapshots, frameworks, guidelines and reports on that topic. Select a topic that you would like to explore.', help_text='A short paragraph helping visitors choose a topic. Use plain text.', verbose_name='Browse by topic introduction'),
        ),
        migrations.CreateModel(
            name='ResourcePageKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_items', to='knowledge_library.resourcepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Internal editorial keywords. These are never shown to visitors.', through='knowledge_library.ResourcePageKeyword', to='taggit.Tag', verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='primary_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_resources', to='knowledge_library.topicpage'),
        ),
        migrations.AddField(
            model_name='resourcepage',
            name='secondary_topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Choose up to two topics, excluding the primary topic.', related_name='secondary_resources', to='knowledge_library.topicpage'),
        ),
    ]
