# Generated by Django 5.2.17 on 2026-09-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_library', '0005_resource_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepage',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, help_text="Reading time in minutes supplied by Wagtail's content metrics.", null=True),
        ),
    ]
